defaults:
  - _self_


experiment:
  seed: 10
  n_samples: 20

  num_epochs: 20
  batch_size: 4 
  lr: 0.001
  kernel_width: 0.01
  early_stop_epochs: 5
  
  shuffle: True
  train_test_split: 0.2

  dataset: "sine" # "sine", "gap" "yacht"
  plot_save_path: "images/regression_plot"

  hidden_layers: [30, 30]

  method: "SVN" # "SVN", "SVGD", "Ensemble"
  n_particles: 5

SVN: 
  red_dist_std: 0.1
  hessian_calc_batch_size: 2
  use_curvature_kernel: "use_curvature"

  hessian_calc: "Full" # "Full", "Diag", "Kron", "LowRank"
  solve_method: "CG" # "Cholesky"