defaults:
  - _self_


experiment:
  seed: 10
  n_samples: 20

  num_epochs: 5
  batch_size: 4 
  lr: 0.001
  kernel_width: 0.01
  
  shuffle: True
  train_test_split: 0.2

  dataset: "sine"
  plot_save_path: "images/regression_plot"

  layer_sizes: [1, 30, 30, 1]

  method: "SVN" # "SVN", "SVGD", "Ensemble"
  n_particles: 4

SVN: 
  red_dist_std: 0.1
  hessian_calc_batch_size: 2
  use_curvature_kernel: "use_curvature"

  hessian_calc: "Full" # "Full", "Diag", "Kron", "LowRank"
  solve_method: "CG" # "Cholesky"