defaults:
  - _self_
  - task: "yacht" # "sine", "gap" "yacht" "energy" "autompg" "concrete" "parkinsons"


experiment:
  seed: 10
  n_splits: 5
  n_samples: 400

  grad_clip: False
  grad_clip_max_norm: 0.1

  wandb_group: 'NeurIPS'

  num_epochs: 50
  batch_size: 16 
  lr: 0.01
  kernel_width: 0.01
  early_stop_epochs: 5

  early_stopping: False

  save_model: False
  base_save_path: '/p/project/hai_baylora/floege1/svn_ensembles/model_checkpoints'
  
  shuffle: True
  train_val_split: 0.20

  plot_save_path: "images/regression_plot"

  hidden_layers: [50, 50]

  method: "SVN" # "SVN", "SVGD", "Ensemble" 
  n_particles: 5

SVN: 
  red_dist_std: 0.1
  hessian_calc_batch_size: 2
  use_curvature_kernel: "use_curvature"

  hessian_calc: "Full" # "Full", "Diag", "Kron", "LowRank"
  solve_method: "CG" # "Cholesky"
  block_diag_approx: False